# Generated by Django 4.2.3 on 2025-09-04 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_contactlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactlist',
            name='detail',
            field=models.TextField(blank=True, null=True),
        ),
    ]
