# Generated by Django 4.2.3 on 2025-09-05 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='userType',
            new_name='usertype',
        ),
    ]
